version: 2
updates:
  - package-ecosystem: github-actions
    versioning-strategy: increase
    directory: /
    schedule:
      interval: daily
    target-branch: master
    labels:
      - dependencies
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: /
    schedule:
      interval: daily
    target-branch: master
    labels:
      - dependencies
